(()=>{
'use strict';
const $x=(s,p=document)=>p.querySelector(s),$$x=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=x=>typeof escapeHtml==='function'?escapeHtml(String(x??'')):String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>`excel_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const text=x=>String(x??'').trim();
const num=x=>{const n=Number(String(x??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
const dateValue=x=>{if(!x)return'';if(typeof x==='number'&&window.XLSX?.SSF?.parse_date_code){const d=XLSX.SSF.parse_date_code(x);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}const s=text(x);const m=s.match(/(20\d{2})[-/.年](\d{1,2})[-/.月](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:s};
const pick=(row,names)=>{for(const n of names)if(row[n]!=null&&text(row[n])!=='')return row[n];return''};
const rowToPublish=(row,fileName,rowNumber)=>({
  id:uid(),market:text(pick(row,['市场','Market']))||'印尼',month:text(pick(row,['Month','月份'])),week:text(pick(row,['Week','周'])),publishDate:dateValue(pick(row,['发布日期','日期','Publish Date','Date'])),account:text(pick(row,['账号','Account'])),dramaTitle:text(pick(row,['片名','剧名','Drama','Title'])),microMarket:text(pick(row,['微剧市场','市场_1','Mini Market']))||'印尼',miniMarket:text(pick(row,['微剧市场','市场_1','Mini Market']))||'印尼',period:text(pick(row,['现/古','现偶/古偶','现古','Period']))||'现代',isIqiyi:text(pick(row,['是否爱奇艺','爱奇艺','iQIYI']))||'否',contentDirection:text(pick(row,['内容制作方向','内容运营方向','Content Direction'])),videoLink:text(pick(row,['视频链接','链接','Video Link','URL'])),views:num(pick(row,['播放量','播放','Views'])),likes:num(pick(row,['点赞量','点赞','Likes'])),followersGained:num(pick(row,['增粉数','增粉','Followers Gained'])),captionOriginal:text(pick(row,['Caption原文','Caption 原文','Caption'])),captionChinese:text(pick(row,['Caption中文','Caption 中文翻译','中文翻译'])),normalHashtags:[],titleHashtag:'',videoStatus:'正常发布',sourceTag:'excel_import',importFileName:fileName,importRowNumber:rowNumber,importedAt:new Date().toISOString(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()
});
const key=r=>[r.publishDate,r.account,r.dramaTitle,r.videoLink||''].map(x=>text(x).toLowerCase()).join('|');
const fallbackKey=r=>[r.publishDate,r.account,r.dramaTitle].map(x=>text(x).toLowerCase()).join('|');
const isDuplicate=r=>(state.publishes||[]).some(x=>key(x)===key(r)||( !r.videoLink&&fallbackKey(x)===fallbackKey(r)));
const isInvalid=r=>!r.publishDate||!r.account||!r.dramaTitle;
let pending=null;
function previewImport(fileName,rows){const mapped=rows.map((r,i)=>rowToPublish(r,fileName,i+2));const fresh=mapped.filter(r=>!isInvalid(r)&&!isDuplicate(r)),dupes=mapped.filter(r=>!isInvalid(r)&&isDuplicate(r)),bad=mapped.filter(isInvalid);pending={fileName,fresh,dupes,bad};showModal('Excel 导入预览',`<div class="excelPreview"><div class="excelSummary"><div><b>${fresh.length}</b><span>预计新增</span></div><div><b>${dupes.length}</b><span>疑似重复</span></div><div><b>${bad.length}</b><span>字段异常</span></div></div><p class="desc">只会导入有效且未重复的记录。Excel 导入的记录会临时显示「Excel 导入」标签；你检查后可直接移除标签。</p>${bad.length?`<div class="excelWarn">字段异常通常是缺少 日期 / 账号 / 片名，本次不会导入。</div>`:''}<div class="heroActions"><button class="btn primary" id="confirmExcelImport" ${fresh.length?'':'disabled'}>确认导入 ${fresh.length} 条</button></div></div>`);$x('#confirmExcelImport')?.addEventListener('click',commitImport)}
function commitImport(){if(!pending?.fresh?.length)return;state.publishes.push(...pending.fresh);try{save()}catch(e){try{storageSet(K,JSON.stringify(state))}catch(_){}}$x('#modal')?.classList.remove('show');try{renderAll()}catch(e){};toast(`已导入 ${pending.fresh.length} 条 Excel 记录`);pending=null;queueEnhance()}
async function readExcel(file){if(!window.XLSX){toast('Excel 读取组件尚未加载，请刷新页面后重试');return}const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:false});const ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});previewImport(file.name,rows)}
function injectImportPanel(){const page=$x('#page-settings');if(!page||$x('#excelImportPanel',page))return;const panel=document.createElement('div');panel.id='excelImportPanel';panel.className='panel excelImportPanel';panel.innerHTML=`<div class="panelHead"><div><h3>Excel 历史数据导入</h3><div class="desc">导入公司历史表格。系统会先预览新增、重复和异常数量，不会直接写入。</div></div></div><div class="heroActions"><label class="btn primary excelFileBtn">选择 Excel<input id="excelImportInput" type="file" accept=".xlsx,.xls,.csv" hidden></label></div>`;page.appendChild(panel);$x('#excelImportInput',panel).onchange=e=>{const file=e.target.files?.[0];if(file)readExcel(file);e.target.value=''}}
const reportHeaders=table=>[...table.querySelectorAll('thead th')].map(th=>text(th.textContent));
const isReport=table=>{const h=reportHeaders(table);return h.includes('日期')&&h.includes('账号')&&h.includes('片名')&&h.includes('操作')};
const findRowRecord=(row,h)=>{const cells=[...row.children],at=n=>{const i=h.indexOf(n);return i>=0?text(cells[i]?.textContent):''};const d=at('日期'),a=at('账号'),t=at('片名');return(state.publishes||[]).find(r=>text(r.publishDate)===d&&text(r.account)===a&&text(r.dramaTitle)===t)||null};
function removeExcelTag(id){const r=(state.publishes||[]).find(x=>x.id===id);if(!r)return;delete r.sourceTag;delete r.importFileName;delete r.importRowNumber;delete r.importedAt;r.updatedAt=new Date().toISOString();try{save()}catch(e){try{storageSet(K,JSON.stringify(state))}catch(_){}}try{renderAll()}catch(e){};toast('Excel 导入标签已移除');queueEnhance()}
function enhanceEditor(){$$x('.reportInlineForm').forEach(form=>{if(form.dataset.excelEnhanced)return;const r=(state.publishes||[]).find(x=>x.id===form.dataset.id);if(!r||r.sourceTag!=='excel_import')return;form.dataset.excelEnhanced='1';const head=form.closest('.reportEditorShell')?.querySelector('.reportEditorHead>div');if(head)head.insertAdjacentHTML('beforeend',`<span class="excelOrigin">Excel 导入 · ${esc(r.importFileName||'历史文件')} · 第 ${Number(r.importRowNumber||0)} 行</span>`);const actions=form.querySelector('.reportEditorActions');if(actions){const b=document.createElement('button');b.type='button';b.className='btn removeExcelTagBtn';b.dataset.id=r.id;b.textContent='移除 Excel 标签';actions.insertBefore(b,actions.firstChild)}})}
function enhanceReport(){document.querySelectorAll('table').forEach(table=>{if(!isReport(table))return;const h=reportHeaders(table),op=h.indexOf('操作');table.querySelectorAll('tbody tr:not(.reportInlineEditor)').forEach(row=>{const r=findRowRecord(row,h);if(!r)return;row.dataset.excelSource=r.sourceTag==='excel_import'?'1':'0';const cell=row.children[op];if(r.sourceTag==='excel_import'&&cell&&!cell.querySelector('.excelImportBadge'))cell.insertAdjacentHTML('afterbegin','<span class="excelImportBadge">Excel 导入</span> ') });let filter=table.parentElement?.parentElement?.querySelector('.excelOnlyFilter');if(!filter){filter=document.createElement('button');filter.type='button';filter.className='btn excelOnlyFilter';filter.textContent='只看 Excel 导入';filter.dataset.active='0';filter.onclick=()=>{filter.dataset.active=filter.dataset.active==='1'?'0':'1';filter.textContent=filter.dataset.active==='1'?'显示全部':'只看 Excel 导入';table.querySelectorAll('tbody tr:not(.reportInlineEditor)').forEach(r=>r.style.display=filter.dataset.active==='1'&&r.dataset.excelSource!=='1'?'none':'')};table.parentElement?.parentElement?.insertBefore(filter,table.parentElement)}});enhanceEditor()}
let queued=false;function queueEnhance(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;injectImportPanel();enhanceReport()})}
document.addEventListener('click',e=>{const b=e.target.closest?.('.removeExcelTagBtn');if(b)removeExcelTag(b.dataset.id)});
new MutationObserver(queueEnhance).observe(document.body,{childList:true,subtree:true});
queueEnhance();
})();
